---
title: "Density and biomass of fish across MPA boundaries in the US Virgin Islands"
author: "Sarah Heidmann"
date: "8/31/2020"
#output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
# Load libraries
library(tidyverse)
library(knitr)
# Import data
dl <- read_csv("data/DeepLion_qaqc_zeros.csv")
# Set colors
mpaColors <- c("#E69F00", "#56B4E9")
inoutColors <- c("#00BE6C","#F8766D")
```

## Summary

This document examines density and biomass of fish communities inside and outside the boundaries of the Hind Bank Marine Conservation District (MCD) and Virgin Islands Coral Reef National Monument (VICRNM).

## Trophic groups

### Density

```{r trophic density, fig.height = 6, fig.width=7, fig.cap="Mean fish density (#/100m^2^) for trophic groups of interest across sites. Error bars represent mean &plusmn; SE."}
# Summarize all fish
totalsum <- dl %>%
     group_by(MPA, InOut, SiteID) %>%
     summarize(totdens = sum(TotalNumber), .groups="drop_last") %>%
     summarize(meandens = mean(totdens),
               sd = sd(totdens),
               n = length(totdens), .groups="drop") %>%
     mutate(sem = sd / sqrt(n))

# Summarize herbivores
herbsum <- dl %>% filter(Troph=="herbivore") %>%
     group_by(MPA, InOut, SiteID) %>%
     summarize(herbdens = sum(TotalNumber), .groups = "drop_last")%>%
     summarize(meandens = mean(herbdens),
                 sd = sd(herbdens),
                 n = length(herbdens), .groups="drop") %>%
     mutate(sem = sd / sqrt(n))

# Summarize piscivores
piscsum <- dl %>% filter(Troph=="piscivore") %>%
     group_by(MPA, InOut, SiteID) %>%
     summarize(piscdens = sum(TotalNumber), .groups = "drop_last") %>%
     summarize(meandens = mean(piscdens),
                 sd = sd(piscdens),
                 n = length(piscdens), .groups="drop") %>%
     mutate(sem = sd / sqrt(n))

# Put them together
denssum <- bind_rows(add_column(totalsum, troph = "all fish"), 
          add_column(herbsum, troph = "herbivores"),
          add_column(piscsum, troph = "piscivores")) %>%
     select(troph, MPA, InOut,meandens, sd, n, sem)
denssum %>% 
     kable(digits = 2, align = "c",
           col.names = c("Trophic Group", "MPA","Location","Mean Density", "SD", "n","SEM"),
           caption = "Mean and variance of fish density (#/100m^2^) for trophic groups of interest across sites.")
ggplot(aes(x= MPA, y = meandens, fill = InOut), data = denssum) +
      geom_bar(stat = "identity", 
               position = position_dodge2(width = 0.9)) +
      geom_errorbar(aes(ymin=meandens-sem, ymax=meandens+sem),
                    width=0.2,position = position_dodge(width = 0.9)) +
   ylab(expression(paste("Mean Density (#/100",m^2,")"))) +
     facet_wrap(~troph, ncol = 1, scales = "free_y") +
   scale_fill_manual(values = inoutColors) +
      theme(panel.background = element_blank(), legend.title = element_blank(),
            axis.line = element_line(), text = element_text(size =16),
            legend.position = "none")

```

### Biomass
```{r trophic biomass, fig.height = 6, fig.width=7, fig.cap="Mean fish biomass (kg/100m^2^) for trophic groups of interest across sites. Error bars represent mean &plusmn; SE."}
# Summarize all fish
totbiosum <- dl %>%
   group_by(MPA, InOut, SiteID) %>%
   summarize(totbio = sum(TotalBiomass, na.rm = T), .groups="drop_last") %>%
   summarize(meanbio = mean(totbio),
             sd = sd(totbio),
             n = length(totbio), .groups="drop") %>%
   mutate(sem = sd / sqrt(n)) %>%
   mutate(meanbiokg = meanbio / 1000, semkg = sem / 1000, sdkg = sd / 1000)

# Summarize herbivores
herbbiosum <- dl %>% filter(Troph=="herbivore") %>%
   group_by(MPA, InOut, SiteID) %>%
   summarize(herbbio = sum(TotalBiomass), .groups = "drop_last") %>%
   summarize(meanbio = mean(herbbio),
             sd = sd(herbbio),
             n = length(herbbio), .groups="drop") %>%
   mutate(sem = sd / sqrt(n)) %>%
   mutate(meanbiokg = meanbio / 1000, semkg = sem / 1000, sdkg = sd / 1000)

# Summarize piscivores
piscbiosum <- dl %>% filter(Troph=="piscivore") %>%
   group_by(MPA, InOut, SiteID) %>%
   summarize(piscbio = sum(TotalBiomass), .groups = "drop_last") %>%
   summarize(meanbio = mean(piscbio),
             sd = sd(piscbio),
             n = length(piscbio), .groups="drop") %>%
   mutate(sem = sd / sqrt(n)) %>%
   mutate(meanbiokg = meanbio / 1000, semkg = sem / 1000, sdkg = sd / 1000)

# Put them together
biosum <- bind_rows(add_column(totbiosum, troph = "all fish"), 
                    add_column(herbbiosum, troph = "herbivores"),
                    add_column(piscbiosum, troph = "piscivores")) %>%
   select(troph, MPA, InOut,meanbiokg, sdkg, n, semkg)
biosum %>% 
   kable(digits = 2, align = "c",
         col.names = c("Trophic Group", "MPA","Location","Mean Biomass (kg)", "SD", "n","SEM"),
         caption = "Mean and variance of fish biomass (kg/100m^2^) for trophic groups of interest across sites.")
ggplot(aes(x= MPA, y = meanbiokg, fill = InOut), data = biosum) +
   geom_bar(stat = "identity", 
            position = position_dodge2(width = 0.9)) +
   geom_errorbar(aes(ymin=meanbiokg-semkg, ymax=meanbiokg+semkg),
                 width=0.2,position = position_dodge(width = 0.9)) +
   ylab(expression(paste("Mean Biomass (kg/100",m^2,")"))) +
   facet_wrap(~troph, ncol = 1, scales = "free_y") +
   scale_fill_manual(values = inoutColors) +
   theme(panel.background = element_blank(), legend.title = element_blank(),
         axis.line = element_line(), text = element_text(size =16),
         legend.position = "none")
```


## Lionfish

### Density

```{r lionfish density, fig.cap="Mean lionfish density (#/100m^2^) across sites. Error bars represent mean &plusmn; SE."}
# Summarize lionfish
lionsum <- dl %>% filter(ScientificName=="Pterois volitans") %>%
     group_by(MPA, InOut) %>% 
     summarize(meandens = mean(TotalNumber),
                  sd = sd(TotalNumber),
                  n = length(TotalNumber), .groups="drop") %>%
     mutate(sem = sd / sqrt(n))
# Print the table
lionsum %>%
     kable(digits = 2, align = "c",
           col.names = c("MPA", "Location", "Mean Density", "SD", "n", "SEM"),
           caption = "Mean and variance of lionfish density (#/100m^2^) across sites.")
# Print the plot
ggplot(aes(x= MPA, y = meandens, fill = InOut), data = lionsum) +
   geom_bar(stat = "identity", 
            position = position_dodge2(width = 0.9)) +
   geom_errorbar(aes(ymin=meandens-sem, ymax=meandens+sem),
                 width=0.2,position = position_dodge(width = 0.9)) +
   ylab(expression(paste("Mean Density (#/100",m^2,")"))) +
   scale_y_continuous(breaks = seq(0,1,0.2), expand = c(0,0)) +
   scale_fill_manual(values = inoutColors) +
   theme(panel.background = element_blank(), legend.title = element_blank(),
         axis.line = element_line(), text = element_text(size =16),
         legend.position = "none")
```

### Biomass
```{r lionfish biomass, fig.cap="Mean lionfish biomass (kg/100m^2^) across sites. Error bars represent mean &plusmn; SE."}
# Summarize lionfish
lionbiosum <- dl %>% filter(ScientificName=="Pterois volitans") %>%
   group_by(MPA, InOut) %>% 
   summarize(meanbio = mean(TotalBiomass),
             sd = sd(TotalBiomass),
             n = length(TotalBiomass), .groups="drop") %>%
   mutate(sem = sd / sqrt(n)) %>%
   mutate(meanbiokg = meanbio / 1000, semkg = sem / 1000, sdkg = sd / 1000)
# Print the table
lionbiosum %>%
   select(MPA, InOut, meanbiokg, sdkg, n, semkg) %>%
   kable(digits = 2, align = "c",
         col.names = c("MPA", "Location", "Mean Biomass (kg)", "SD", "n", "SEM"),
         caption = "Mean and variance of lionfish biomass (kg/100m^2^) across sites.")
# Print the plot
ggplot(aes(x= MPA, y = meanbiokg, fill = InOut), data = lionbiosum) +
   geom_bar(stat = "identity", 
            position = position_dodge2(width = 0.9)) +
   geom_errorbar(aes(ymin=meanbiokg-semkg, ymax=meanbiokg+semkg),
                 width=0.2,position = position_dodge(width = 0.9)) +
   ylab(expression(paste("Mean Biomass (kg/100",m^2,")"))) +
   scale_y_continuous(breaks = seq(0,0.4, 0.1), expand = c(0,0)) +
   scale_fill_manual(values = inoutColors) +
   theme(panel.background = element_blank(), legend.title = element_blank(),
         axis.line = element_line(), text = element_text(size =16),
         legend.position = "none")
```

## Groups of interest

### Density
```{r group density, fig.width = 7.5, fig.height = 7, fig.cap="Mean fish density (#/100m^2^ &plusmn; SE) across sites for all lionfish and other groups of interest, separated by MPA and inside/outside MPA boundaries. Groups were adapted from Green et al (2012)."}
groupnames <- names(dl)[46:55]
groupdensnames <- groupnames[seq(1,9,2)]
groupbionames <- groupnames[seq(2,10,2)]

grouplabels <- tibble(group = c(groupdensnames, "Lionfish"),
                      grouplabel = c("Large-bodied non-predator","Large-bodied predator",
                 "Non-reef associated","Small-bodied non-prey","Small-bodied prey",
                 "Lionfish"))

groupsum <- dl %>%
   pivot_longer(cols=all_of(groupnames), names_to = "group") %>%
   mutate(type = ifelse(group %in% groupdensnames, "density", "biomass"),
          group = gsub(".biomass","",group)) %>%
   pivot_wider(id_cols = c("SiteID","MPA", "InOut","group"),
               names_from = type, values_from = value, values_fn = sum) %>%
   group_by(MPA, InOut, group) %>%
   summarize(meandens = mean(density),
             sddens = sd(density),
             ndens = length(density),
             meanbio = mean(biomass),
             sdbio = sd(biomass),
             nbio = length(biomass), .groups = "drop") %>%
   mutate(semdens = sddens / sqrt(ndens), sembio = sdbio / sqrt(nbio))

grouplionsum <- bind_cols(rename(lionsum, sddens = sd, ndens = n, semdens = sem), 
                          select(lionbiosum, meanbio,sdbio=sd,nbio=n,sembio=sem)) %>%
   add_column(group = "Lionfish") %>%
   select(names(groupsum)) %>%
   bind_rows(groupsum) %>%
   mutate(meanbiokg = meanbio / 1000, sembiokg = sembio / 1000) %>%
   left_join(grouplabels, by="group")

ggplot(aes(x= MPA, y = meandens, fill = InOut), data = grouplionsum) +
   geom_bar(stat = "identity", 
            position = position_dodge2(width = 0.9)) +
   geom_errorbar(aes(ymin=meandens-semdens, ymax=meandens+semdens),
                 width=0.2, position = position_dodge(width = 0.9)) +
   ylab(expression(paste("Mean Density (#/100",m^2,")"))) +
   facet_wrap(~grouplabel,ncol=2,scales="free_y") +
   scale_y_continuous(expand = c(0,0)) +
   scale_fill_manual(values = inoutColors) +
   theme(panel.background = element_blank(), legend.title = element_blank(),
         axis.line = element_line(), text = element_text(size =16),
         legend.position = "none")


```

### Biomass
```{r group biomass, fig.width = 7.5, fig.height = 7, fig.cap="Mean fish biomass (kg/100m^2^ &plusmn; SE) across sites for all lionfish and other groups of interest, separated by MPA and inside/outside MPA boundaries. Groups were adapted from Green et al (2012)."}
ggplot(aes(x= MPA, y = meanbiokg, fill = InOut), data = grouplionsum) +
   geom_bar(stat = "identity", 
            position = position_dodge2(width = 0.9)) +
   geom_errorbar(aes(ymin=meanbiokg-sembiokg, ymax=meanbiokg+sembiokg),
                 width=0.2, position = position_dodge(width = 0.9)) +
   ylab(expression(paste("Mean Biomass (kg/100",m^2,")"))) +
   facet_wrap(~grouplabel,ncol=2,scales="free_y") +
   scale_y_continuous(expand = c(0,0)) +
   scale_fill_manual(values = inoutColors) +
   theme(panel.background = element_blank(), legend.title = element_blank(),
         axis.line = element_line(), text = element_text(size =16),
         legend.position = "none")
```



## Families
```{r family biomass, fig.fullwidth = TRUE, fig.height = 8, fig.cap="Mean fish family biomass (kg/100m^2^ &plusmn; SE) across sites, separated by MPA and inside/outside MPA boundaries."}
fambio <- dl %>%
   group_by(MPA, InOut, Family, SiteID) %>% 
   summarize(totbio = sum(TotalBiomass, na.rm = T), .groups = "drop_last") %>%
   summarize(meanbio = mean(totbio),
             sd = sd(totbio),
             n = length(totbio), .groups="drop") %>%
   mutate(sem = sd / sqrt(n)) %>%
   mutate(meanbiokg = meanbio / 1000, semkg = sem / 1000) %>%
   mutate(MPAInOut = paste0(as.character(MPA), " ", as.character(InOut)))

ggplot(aes(x= Family, y = meanbiokg), data = fambio) +
   geom_bar(stat = "identity") +
   geom_errorbar(aes(ymin=meanbiokg-semkg, ymax=meanbiokg+semkg), width = 0.5) +
    ylab(expression(paste("Mean Biomass (kg/100",m^2,")"))) +
   scale_y_continuous(expand = c(0,0)) +
   facet_wrap(~MPAInOut, ncol=1) +
   theme(panel.background = element_blank(), legend.title = element_blank(),
         axis.line = element_line(), text = element_text(size =16),
         legend.position = "top", 
         axis.text.x = element_text(angle = -90, size = 10, hjust=0))
```

