---
title: "DeepLion"
author: "Sarah Heidmann"
date: "9/4/2020"
output: html_document
---

This study is not yet published.

**Funding:** NOAA-CRCP NA17NOS4820086

**Project Title:** Testing the efficacy of MPAs and the impact of invasive lionfish on mesophotic reefs in the US Virgin Islands

*Principal Investigator:* Dr. Richard Nemeth, University of the Virgin Islands

**Executive Summary**\
In the United States Virgin Islands (USVI), mesophotic coral ecosystems (MCE) are important deep reef habitats supporting corals and reef fish at depths greater than 30m. These reef systems are more extensive than previously thought and represent > 75% of coral reef area in the USVI. Two large marine reserves, Red Hind Bank Marine Conservation District (MCD) and Virgin Islands Coral Reef National Monument (VICRNM) include extensive MCE habitats, that are largely unstudied relative to shallow coral reefs due to diving limitations. There is an urgency to understanding MCE because long-term monitoring has found that mesophotic reefs are supporting large populations of the invasive lionfish (*Pterois volitans*), making culling-based management on shallow reefs ineffective. This research had two primary goals. The first goal was to examine the efficacy of the large MPAs in improving fishery resources by conducting a comparative assessment of biological resources including fish populations (abundance, biomass and diversity) and benthic habitats (benthic cover and coral health) inside and outside the MCD and VICRNM. The second goal was to examine changes in these resources before and after the arrival of the invasive lionfish by comparing historical data from these sites to more recently collected data several years after the arrival of lionfish.\
Between February 2018 and March 2019, 121 sites were surveyed inside and outside VICRNM and MCD and compared to historical data collected in 2002-2006 and 2007-2008, respectively. Percent cover of live coral, gorgonians, and sponges declined between the first and second sampling periods inside and outside VICRNM but were relatively stable inside and outside MCD. This pattern may have largely been an artifact of when surveys were conducted since VICRNM sites were all surveyed before the 2005-2006 mass bleaching and disease event that caused large-scale mortality of shallow and mesophotic coral reefs around the USVI. The MCD surveys were conducted after this mortality event in 2007-2008. The biomass of all fishes, and piscivore and herbivore trophic groups were relatively unchanged across time periods inside and outside both MPAs.\
Lionfish densities were not significantly different inside and outside the MPA’s, but were significantly higher around the MCD (inside and outside) than around the VICRNM. This may have resulted from the MCD being deeper (mean = 39.6 m) with higher rugosity (102 cm relief) than VICRNM (mean depth = 25.4 m, mean rugosity = 38 cm relief). We found a significant positive relationship between lionfish biomass and depth within the MCD but no relationship with depth and lionfish density, indicating that larger lionfish tended to be on deeper reefs. No relationship was found between density or biomass of lionfish and small-bodied prey fish, potential lionfish predators or other functional groups nor an effect on percent coral cover among our study sites. The lack of any clear patterns from these analyses suggest that at the time of our recent surveys, lionfish density and biomass has had no clear direct or indirect impacts on native fish populations or coral health on mesophotic reefs.